# Generated by Django 4.2.9 on 2026-01-01 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, help_text="Stock price", max_digits=15
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(default=0, help_text="Trading volume"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ALPHA_VANTAGE", "Alpha Vantage API"),
                            ("MANUAL", "Manual Entry"),
                            ("YAHOO", "Yahoo Finance"),
                            ("POLYGON", "Polygon.io"),
                        ],
                        default="ALPHA_VANTAGE",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="When this price was recorded"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Price",
                "verbose_name_plural": "Stock Prices",
                "db_table": "stock_prices",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-timestamp"],
                        name="stock_price_stock_i_65ec2e_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="stock_price_timesta_46bf57_idx"
                    ),
                    models.Index(
                        fields=["source"], name="stock_price_source_2f8a78_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stockprice",
            constraint=models.UniqueConstraint(
                fields=("stock", "timestamp"), name="unique_stock_price_timestamp"
            ),
        ),
    ]
