# Generated by Django 4.2.9 on 2026-01-01 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist",
                "verbose_name_plural": "Watchlists",
                "db_table": "watchlists",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_thresholds",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Alert thresholds in JSON format",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_items",
                        to="stocks.stock",
                    ),
                ),
                (
                    "watchlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="watchlists.watchlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist Item",
                "verbose_name_plural": "Watchlist Items",
                "db_table": "watchlist_items",
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["watchlist", "-added_at"],
                        name="watchlist_i_watchli_848702_idx",
                    ),
                    models.Index(
                        fields=["stock"], name="watchlist_i_stock_i_c3f9c6_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="watchlistitem",
            constraint=models.UniqueConstraint(
                fields=("watchlist", "stock"), name="unique_watchlist_stock"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(
                fields=["user", "is_default"], name="watchlists_user_id_f891df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlist",
            index=models.Index(
                fields=["user", "-created_at"], name="watchlists_user_id_ba7d11_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="watchlist",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_watchlist_name"
            ),
        ),
    ]
