# Generated by Django 4.2.9 on 2026-01-01 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("NYSE", "New York Stock Exchange"),
                            ("NASDAQ", "NASDAQ"),
                            ("NSE", "National Stock Exchange of India"),
                            ("BSE", "Bombay Stock Exchange"),
                            ("LSE", "London Stock Exchange"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "market_cap",
                    models.BigIntegerField(
                        blank=True, help_text="Market cap in millions", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "db_table": "stocks",
                "ordering": ["symbol"],
                "indexes": [
                    models.Index(fields=["symbol"], name="stocks_symbol_7bc68d_idx"),
                    models.Index(fields=["exchange"], name="stocks_exchang_74d758_idx"),
                    models.Index(
                        fields=["is_active"], name="stocks_is_acti_fcb4d4_idx"
                    ),
                    models.Index(
                        fields=["exchange", "is_active"],
                        name="stocks_exchang_d690c7_idx",
                    ),
                ],
            },
        ),
    ]
